import multer from 'multer';
import path from 'path';
import fs from 'fs';
import { v2 as cloudinary } from 'cloudinary';

// Configure Cloudinary with your .env variables
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const UPLOAD_DIR = path.join(process.cwd(), 'uploads');

// Ensure upload directory exists
if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
}

// Multer Disk Storage Configuration
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, UPLOAD_DIR);
  },
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
    cb(null, file.fieldname + '-' + uniqueSuffix + path.extname(file.originalname));
  }
});

export const upload = multer({ 
  storage,
  limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

export interface UploadResult {
  /** URL the frontend should render. */
  url: string;
  /**
   * True when the upload fell back to local disk, meaning `localFilePath` IS the
   * served asset and the caller must NOT delete it. Callers that blindly unlink
   * the temp file after uploading would otherwise leave a dead /uploads/ URL.
   */
  storedLocally: boolean;
}

/**
 * Cloud Storage Adapter Function (Cloudinary)
 * Takes the local file path generated by Multer, uploads it to Cloudinary, and
 * returns the secure cloud URL. If Cloudinary is unconfigured or errors, it
 * degrades to serving the file from the local /uploads route instead.
 */
export async function uploadToCloud(localFilePath: string): Promise<UploadResult> {
  try {
    // Check if Cloudinary is configured (prevents crashes for teammates without .env setup)
    if (!process.env.CLOUDINARY_API_KEY) {
      throw new Error('Cloudinary keys missing');
    }

    const result = await cloudinary.uploader.upload(localFilePath, {
      folder: 'civicforge_media',
      resource_type: 'auto', // Automatically detects and handles images vs audio files
    });

    return { url: result.secure_url, storedLocally: false };

  } catch (error) {
    console.warn('Cloudinary upload bypassed or failed, serving the file from local storage instead:', error);

    // MVP Fallback: serve the file straight off disk via app.use('/uploads', ...).
    // storedLocally tells the caller to keep the file where it is.
    const filename = path.basename(localFilePath);
    return { url: `/uploads/${filename}`, storedLocally: true };
  }
}