import multer from 'multer';
import path from 'path';
import fs from 'fs';
import { v2 as cloudinary } from 'cloudinary';

// Configure Cloudinary with your .env variables
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const UPLOAD_DIR = path.join(process.cwd(), 'uploads');

// Ensure upload directory exists
if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
}

// Multer Disk Storage Configuration
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, UPLOAD_DIR);
  },
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
    cb(null, file.fieldname + '-' + uniqueSuffix + path.extname(file.originalname));
  }
});

export const upload = multer({ 
  storage,
  limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

/**
 * Cloud Storage Adapter Function (Cloudinary)
 * Takes the local file path generated by Multer, uploads it to Cloudinary,
 * and returns the secure cloud URL.
 */
export async function uploadToCloud(localFilePath: string): Promise<string> {
  try {
    // Check if Cloudinary is configured (prevents crashes for teammates without .env setup)
    if (!process.env.CLOUDINARY_API_KEY) {
      throw new Error('Cloudinary keys missing');
    }

    const result = await cloudinary.uploader.upload(localFilePath, {
      folder: 'civicforge_media',
      resource_type: 'auto', // Automatically detects and handles images vs audio files
    });
    
    return result.secure_url;
    
  } catch (error) {
    console.warn('Cloudinary upload bypassed or failed, falling back to local storage URL:', error);
    
    // MVP Fallback: Return a locally resolvable relative URL so frontend doesn't break
    const filename = path.basename(localFilePath);
    return `/uploads/${filename}`;
  }
}